import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarPembeli from '../components/NavbarPembeli'; 
import Navbar from '../components/Navbar';
import NavbarAdmin from '../components/NavbarAdmin'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const situasi = "pembeli"; 
  
  let navbarComponent
  if (situasi === 'pembeli') {
    navbarComponent = <NavbarPembeli />;
  } else if (situasi === 'sebelum') {
    navbarComponent = <Navbar />;
  } else if (situasi === 'admin') {
    navbarComponent = <NavbarAdmin />;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {navbarComponent}
        <div className="mt-20">{children}</div> 
      </body>
    </html>
  );
}

